import { Product } from '@/types';

export const products: Product[] = [
  {
    id: 1,
    name: 'Classic Crewneck T-Shirt',
    category: 'Men',
    price: 25.00,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=2080&auto=format&fit=crop',
    description: 'A timeless classic, this crewneck t-shirt is made from premium, soft-touch cotton for ultimate comfort.',
    featured: true,
  },
  {
    id: 2,
    name: 'Slim-Fit Chinos',
    category: 'Men',
    price: 65.00,
    image: 'https://images.unsplash.com/photo-1602293589914-9e296ba2a7c4?q=80&w=1935&auto=format&fit=crop',
    description: 'Versatile and stylish, these slim-fit chinos are perfect for any occasion, from casual outings to smart-casual events.',
  },
  {
    id: 3,
    name: 'Flowy Maxi Dress',
    category: 'Women',
    price: 85.00,
    image: 'https://images.unsplash.com/photo-1594665497493-3e3bff718b35?q=80&w=1964&auto=format&fit=crop',
    description: 'Elegant and comfortable, this flowy maxi dress features a beautiful floral print and a flattering silhouette.',
    featured: true,
  },
  {
    id: 4,
    name: 'High-Waisted Skinny Jeans',
    category: 'Women',
    price: 75.00,
    image: 'https://images.unsplash.com/photo-1604176354204-926873782855?q=80&w=1964&auto=format&fit=crop',
    description: 'A wardrobe staple, these high-waisted skinny jeans are designed to hug your curves and provide all-day comfort.',
  },
  {
    id: 5,
    name: 'Leather Crossbody Bag',
    category: 'Accessories',
    price: 120.00,
    image: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?q=80&w=1935&auto=format&fit=crop',
    description: 'Crafted from genuine leather, this crossbody bag is the perfect accessory to complete your look.',
    featured: true,
  },
  {
    id: 6,
    name: 'Minimalist Watch',
    category: 'Accessories',
    price: 150.00,
    image: 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?q=80&w=2080&auto=format&fit=crop',
    description: 'With its clean and modern design, this minimalist watch adds a touch of sophistication to any outfit.',
  },
  {
    id: 7,
    name: 'Linen Button-Up Shirt',
    category: 'Men',
    price: 55.00,
    image: 'https://images.unsplash.com/photo-1621072156002-e2fccdc0b176?q=80&w=1935&auto=format&fit=crop',
    description: 'Stay cool and stylish in this lightweight linen button-up shirt, perfect for warm weather.',
  },
  {
    id: 8,
    name: 'Silk Blend Blouse',
    category: 'Women',
    price: 95.00,
    image: 'https://images.unsplash.com/photo-1581865579092-b7558c8246f5?q=80&w=1964&auto=format&fit=crop',
    description: 'Luxurious and versatile, this silk blend blouse drapes beautifully and feels incredibly soft against the skin.',
    featured: true,
  },
];